services:
  web:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    command: /bin/sh -c "python /app/fintrackr/manage.py migrate && python /app/fintrackr/manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./gui
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./gui:/app
    environment:
      - VUE_APP_API_URL=http://web:8000

  db:
    image: mysql:9.1
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
