# Generated by Django 5.1.3 on 2024-11-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categories_expenses_expensecategories_incomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='source',
        ),
        migrations.CreateModel(
            name='IncomeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incomes')),
            ],
        ),
    ]
