# Generated by Django 5.1.4 on 2024-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_debts_debtcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='debtor_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
