# Generated by Django 5.1.4 on 2024-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debts_debtor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incomes',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
