# Generated by Django 5.1.4 on 2024-12-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_debts_icon_expenses_icon_incomes_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomes',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
