# Generated by Django 5.1.4 on 2024-12-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_incomes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
